---
title: "Pruebas Admisión ICAI"
output:
  slidy_presentation: 
    includes:
      in_header: startTime.html
    self-contained: yes
  ioslides_presentation:
    includes:
      in_header: startTime.html
    self-contained: yes
date: '2023'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

---

### Instrucciones Generales

<h3><div id="txt1"></div></h3>

 + **Comprueba que la carpeta que hay en tu mesa coincide con tu número de solicitud y examina su contenido.**
 + Pon tu DNI o pasaporte encima de la mesa.
 + Los móviles deben estar apagados y guardados. 
 + No se puede utilizar calculadora en ninguna prueba.
 + Asegúrate de elegir la hoja de respuestas correspondiente a cada prueba.
 + Puedes utilizar cualquier parte de los cuadernillos para operaciones en sucio, *excepto en la prueba Psicotécnica* donde te facilitaremos papel.
 + Necesitarás lápiz, sacapuntas y goma de borrar.
 + No se penalizan las respuestas incorrectas en ninguna prueba.
 + Marca tus respuestas en la hoja tras cada ejercicio. **!!No esperes al final, puede que no te de tiempo a marcarlas!!**
 + Al marcar en la hoja de respuestas no aprietes demasiado (para que puedas borrar si es necesario) ni demasiado poco (que no haya errores de lectura). Usa la goma si es necesario, no uses ningún tipo de corrector.
 + Los resultados de las pruebas serán comunicados en 15 días.


---

### Instrucciones Prueba Matemáticas

<h3><div id="txt2"></div></h3>

 + <span style = "color:red"> DNI o pasaporte encima de la mesa.</span>
 + <span style = "color:red"> Asegúrate de elegir la hoja de respuestas correspondiente a esta prueba.</span>
 + <span style = "color:red"> Duración: 45 minutos, de 9:00 a 9:45. </span>
 + <span style = "color:red"> Responder a 12 de las 15 preguntas (se corrigen las 12 primeras respuestas). Respeta el número de pregunta en la hoja de respuestas. </span>
 + <span style = "color:red"> No se penalizan las respuestas incorrectas (no marques menos de 12 respuestas).</span>
 + <span style = "color:red"> Marca tus respuestas en la hoja tras cada ejercicio, no esperes al final.</span>
 + Los móviles deben estar apagados y guardados.
 + No se puede utilizar calculadora en ninguna prueba.

<!-- ##################################################################################################################### --> 
<!-- ##################################################################################################################### --> 
<!-- ##################################################################################################################### --> 

---

### Instrucciones Prueba Física

<h3><div id="txt3"></div></h3>

 + <span style = "color:red"> Asegúrate de elegir la hoja de respuestas correspondiente a esta prueba.</span>
 + <span style = "color:red"> Duración: 45 minutos, de 9:50 a 10:35. </span>
 + <span style = "color:red"> Responde a 15 de las 18 preguntas. (se corrigen las 15 primeras respuestas). Respeta el número de pregunta en la hoja de respuestas. </span>
 + <span style = "color:red"> No se penalizan las respuestas incorrectas (no marques menos de 15 respuestas).</span>
 + <span style = "color:red"> Marca tus respuestas en la hoja tras cada ejercicio, no esperes al final.</span>
 + Los móviles deben estar apagados y guardados.
 + No se puede utilizar calculadora en ninguna prueba.

<!-- ##################################################################################################################### --> 
<!-- ##################################################################################################################### --> 
<!-- ##################################################################################################################### --> 


---

### Descanso: 10:35 – 11:05

<h3><div id="txt4"></div></h3>

 + <span style = "color:red"><b>IMPORTANTE: No te lleves cuadernillos ni hojas de respuesta, déjalos en la mesa.</b></span>
 + <span style = "color:red"> ¡¡Asegúrate de estar de vuelta en tu mesa a las 11:05!!</span>
 + <span style = "color:red"> Evita las aglomeraciones en los pasillos</span>
 + <span style = "color:red"> Procura no abandonar el edificio. </span>

---

### Instrucciones Prueba Psicotécnica

<h3><div id="txt5"></div></h3>

 + <span style = "color:red"><b>IMPORTANTE: No escribir en los cuadernillos. Usa los folios en blanco que se repartirán.</b></span>
 + <span style = "color:red"><b>En esta prueba hay cinco respuestas por pregunta, sólo una es válida.</b></span>
 + <span style = "color:red"> Duración: 15 minutos (11:15-11:30). </span>
 + <span style = "color:red"> Asegúrate de elegir la hoja de respuestas correspondiente a esta prueba.</span>
 + <span style = "color:red"> Marca tus respuestas en la hoja tras cada ejercicio, no esperes al final.</span>
 <!-- + <span style = "color:red"> Responde a 15 de las 18 preguntas. (se corrigen las 15 primeras respuestas). Respeta el número de pregunta en la hoja de respuestas. </span> -->
 + <span style = "color:red"> No se penalizan las respuestas incorrectas (no marques menos de 15 respuestas).</span>
 + <span style = "color:red"><b>Recuerda apagar y guardar el móvil.</b></span>
 + No se puede utilizar calculadora en ninguna prueba.

---

### Instrucciones Prueba Inglés

<h3><div id="txt6"></div></h3>

 + <span style = "color:red"> Duración: 25 minutos (11:35-12:00). </span>
 + <span style = "color:red"> Asegúrate de elegir la hoja de respuestas correspondiente a esta prueba.</span>
 + <span style = "color:red"> No se penalizan las respuestas incorrectas (no marques menos de 15 respuestas).</span>
 + <span style = "color:red"> Marca tus respuestas en la hoja tras cada ejercicio, no esperes al final.</span>
 

---

### Final de las Pruebas 12:00

<h3><div id="txt7"></div></h3>

 + Recuerda que debes salir del edificio por la misma puerta que usaste para entrar.
 + ¡Evita las aglomeraciones en la entrada!
 + Los resultados de las pruebas serán comunicados en 15 días. No llames antes, porque no podrán darte información.

